### ISSUE TITLE
Can I moniting only harvester?

### ISSUE THREAD

**Issue by KevinMyDing** [philippnormann/chia-monitor#2]
I hava 4 harvester machine, these machines only running harvester, because they connect another full_node machine.

So, Can I moniting only harvester?

**Comment by philippnormann** [comment]
Currently, the RpcCollector and WsCollector expect a full node, farmer, harvester and wallet  to be running on the same machine as the chia-monitor. But it should be quite easy to change it, so that the collectors simply collect what they can and ignore connection errors to the other daemons. I'll see what I can do :)

**Comment by rjsears** [comment]
This looks very promising. I have a bunch of drive alerting and plot monitoring already built into my system (https://github.com/rsears/chia_plot_manager) and I was literally in the process of building something like this to export to grafana (not using the API but my own exports) but from the standpoint of a single farmer/full node and many harvesters (my setup) to integrate with my code. This looks very promising if you could get it to work for multiple harvesters. I might fork it and play around with it.

**Comment by philippnormann** [comment]
Hey @rjsears, I am glad you like it! After a bit more digging into [the code of Chia](https://github.com/Chia-Network/chia-blockchain/blob/c1f54cb13afd035046dffbb5bcdd13affd811ed8/chia/harvester/harvester_api.py#L225), I discovered that the farming_info event including all interesting information like plot count, filters passed and found proofs is actually sent to the farmer node. This event is already being collected through the existing WsCollector on the farmer. So a LogExporter is probably not even necessary.

**Comment by KevinMyDing** [comment]
I forked this project, and I already finished it. But it still needs to be tested.    

https://github.com/KevinMyDing/chia-monitor/commit/5e44f4d71abf900312ed4852db712a5583287062

> Hey @rjsears, I am glad you like it! After a bit more digging into [the code of Chia](https://github.com/Chia-Network/chia-blockchain/blob/c1f54cb13afd035046dffbb5bcdd13affd811ed8/chia/harvester/harvester_api.py#L225), I discovered that the farming_info event including all interesting information like plot count, filters passed and found proofs is actually sent to the farmer node. This event is already being collected through the existing WsCollector on the farmer. So a LogExporter is probably not even necessary. 
> 
> 
> 
> We should still implement a way to scrape the RPC Endpoints of all connected harvesters to get a total plot size, since this information is not included in the farming info events.

**Comment by philippnormann** [comment]
Awesome! That `get_plots` code looks very familiar 😄 

If you could rebase your changes on main and create a PR, I would be happy to merge it. Also, I would prefer if you could rewrite the code, so that the harvester RPC clients don't get recreated on every request and instead are created using the config that was already passed to the `__init__` method, like it is currently already done for the other clients.

**Comment by philippnormann** [comment]
That's correct. The latest commit https://github.com/philippnormann/chia-monitor/commit/df86f16472ff8d10026b8162282d698f765e0780 adds this functionality and scrapes all connected harvesters RPC endpoints to get their exact capacity. In order for this to work you need to change the `self_hostname` in the `config.yaml` on the harvesters to `0.0.0.0`, so they can be reached from the farmer machine on which the chia-monitor is running. 

Since the tool can now handle running only on a harvester machine and can also monitor harvesters from the farmer node directly, I consider this issue resolved. Please feel free to reopen a new issue if you have any other suggestions or bug reports!
