### ISSUE TITLE
chives-monitor?

### ISSUE THREAD

**Issue by efkay1** [philippnormann/chia-monitor#54]
Hi, I just installed chia-monitor and it is great! I'd like to also use this for chives (chiafork). can somebody tell me what to change in chia-monitor to be able to monitor both coins in parallel?

best regards

**Comment by philippnormann** [comment]
Hey @efkay1, I haven't experimented with any Chia forks yet... You probably only need to adjust the `CHIA_ROOT` environment variable, but since supporting forks is out of the scope of this project, you will need to figure out the details on your own. Maybe someone on the Discord server has already got this working and might help you with it in the #support channel.
